### ISSUE TITLE
I use CPU test demo.py with  your mobilenetv2-based model .Why reasoning inference in 1fps per frame. 

### ISSUE THREAD

**Issue by JH95-ai** [zengwbz/Face-Tracking-usingFairMOT#2]
First, thanks your finish an amazing project.My problems describe as title.Is there something I didn't do that made it slow? Or that's the velocity of this model.
 Looking forward to your reply.

**Comment by JH95-ai** [comment]
today,I make face data for train use CASIA-Webface dataset.Epoch set 30.Finally,total loss is 1.0 ,re-id loss is 6.37.I want ask that what is your loss value.and your inference speed per frame.Thanks.

**Comment by zengwb-lx** [comment]
80fps in 2070GPU，Ｉhave writen finally loss in my blog



发自我的iPhone


------------------ Original ------------------

**Comment by JH95-ai** [comment]
That's ok.Thanks your reply..
